services:
  # Database Service (SQL Server)
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: printoscar_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@9-qNabWXD83
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  # Backend Service (.NET API)
  api:
    build:
      context: ./segishop-api/SegishopAPI
      dockerfile: Dockerfile
    container_name: printoscar_api
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=SegishopDB;User Id=sa;Password=@9-qNabWXD83;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  # Frontend Service (Next.js)
  web:
    build:
      context: ./segishop
      dockerfile: Dockerfile
    container_name: printoscar_web
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    depends_on:
      - api

volumes:
  sqlvolume:
