services:
  # Database Service (SQL Server)
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: printoscar_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@9-qNabWXD83
      - MSSQL_PID=Express
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P @9-qNabWXD83 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s
    ports:
      - "127.0.0.1:1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  # Backend Service (.NET API)
  api:
    build:
      context: ./segishop-api/SegishopAPI
      dockerfile: Dockerfile
    container_name: printoscar_api
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=printoscar_db;Database=SegishopDB_Dev;User Id=sa;Password=@9-qNabWXD83;TrustServerCertificate=True;MultipleActiveResultSets=true;
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db:
        condition: service_healthy

  # Frontend Service (Next.js)
  web:
    build:
      context: ./segishop
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://printoscarapi.xendekweb.com
    container_name: printoscar_web
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://printoscarapi.xendekweb.com
    depends_on:
      - api

volumes:
  sqlvolume:
